TerrorData=[
    {
        Country:{
            Name: 'Nigeria',
            State:{
                Maiduguri: {
                    id: 1,
                    Year: ['11-14-20', '14-1-14'],
                    city: ['Maiduguri'],
                    perpetraitors: 'Boko-Haram',
                    fatality: [3, 18]
                },
                Lagos: {
                    id:2,
                    Year: ['14-6-20', '3-4-17'],
                    city: ['Lagos', 'Alaba'],
                    perpetraitors:['Boko-Haram', 'Fulani-Hearders',],
                    fatality: [5,8],
                },
                Benue: {
                    id:3,
                    Year: ['14-6-20', '2-4-17', '11-5-15', '20-4-15'],
                    city: ['Aboughul', 'Turan Kwale', 'Tse- Gbaun'],
                    perpetraitors:'Fulani-Hearders',
                    fatality: [3,15,5,5],
                },
                Nasarawa: {
                    id:4,
                    Year: ['14-6-20'],
                    city: ['Lafia','Gudi'],
                    perpetraitors:'Fulani-Hearders',
                    fatality:[1,2],
                },
                Borno: {
                    id:5,
                    Year: ['14-6-20', '1-2-19', '17-6-18','7-11-16'],
                    city: ['Banki', 'Baga', 'Biu', 'Danboa', 'Kangarwa'],
                    perpetraitors:'Boko-Haram',
                    fatality: [5,0,0,37,14],
                },
                Plateau: {
                    id:6,
                    Year: ['14-6-20','5-3-14'],
                    city: ['Riyom', 'Gida-Bua', 'Torok'],
                    perpetraitors:'Fulani-Hearders',
                    fatality: [0,3,3],
                },
                Ondo: {
                    id:7,
                    Year: ['14-6-20'],
                    city: 'Akure North',
                    perpetraitors:'Fulani-Hearders',
                    fatality: 0,
                },
                Niger: {
                    id:8,
                    Year: ['8-2-20'],
                    city: ['Ashirika', 'Old Gurmana', 'Gurmana'],
                    perpetraitors:'Boko-Haram',
                    fatality: [1,1,1],
                },
                Kaduna: {
                    id:9,
                    Year: ['25-1-20','17-4-19'],
                    city: ['Juji', 'Sabon Gari'],
                    perpetraitors:'Boko-Haram',
                    fatality: [1, 0],
                },
                Enugu: {
                    id:10,
                    Year: ['18-7-19'],
                    city: ['Nkanu East District'],
                    perpetraitors:'Fulani-Hearders',
                    fatality: 0,
                },
                Bauchi: {
                    id:11,
                    Year: ['16-6-18'],
                    city: 'Shawari',
                    perpetraitors:'Boko-Haram',
                    fatality: 4,
                },
                Taraba: {
                    id:12,
                    Year: ['28-5-18', '8-5-16','20-4-15'],
                    city: ['Jalingo','Gidan Bature','Orawua', 'Korun', 'Gaza',' Ayiase'],
                    perpetraitors:['Fulani-Hearders', 'Boko-Haram'],
                    fatality: [0, 2,5,15],
                },
                Edo: {
                    id:13,
                    Year: ['29-3-18'],
                    city: 'Ovia North East',
                    perpetraitors:'Fulani-Hearders',
                    fatality: 1,
                },
                Kano: {
                    id:14,
                    Year: ['28-7-17'],
                    city: 'Gaya',
                    perpetraitors:'Boko-Haram',
                    fatality: 1,
                },
                Abuja: {
                    id:15,
                    Year: ['21-12-16'],
                    city: 'Kwali',
                    perpetraitors:'Fulani-Hearders',
                    fatality: 0,
                },
                Delta: {
                    id:16,
                    Year: ['21-12-16'],
                    city: 'Warri',
                    perpetraitors:'Fulani-Hearders',
                    fatality: 0,
                },
                Ekiti: {
                    id:17,
                    Year: ['20-4-16'],
                    city: 'Oke Ako',
                    perpetraitors:'Fulani-Hearders',
                    fatality: 2,
                },
                Jigawa: {
                    id:18,
                    Year: ['5-3-14'],
                    city: 'Gwaram',
                    perpetraitors:'Fulani-Hearders',
                    fatality: 3,
                },
                Kogi: {
                    id:19,
                    Year: ['6-5-15'],
                    city: 'Adavi District',
                    perpetraitors: 'Fulani-Hearders',
                    fatality: 1,
                },
                Lagos: {
                    id:20,
                    Year: ['14-6-20'],
                    city: 'Lagos',
                    perpetraitors:'Boko-Haram',
                    fatality: 5,
                },
                Lagos: {
                    id:21,
                    Year: ['14-6-20'],
                    city: 'Lagos',
                    perpetraitors:'Boko-Haram',
                    fatality: 5,
                },
                Lagos: {
                    id:22,
                    Year: ['14-6-20'],
                    city: 'Lagos',
                    perpetraitors:'Boko-Haram',
                    fatality: 5,
                },

            }
        }
    },
];